In [1]:
# Importacion de librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Leer archivo fuente de datos
data = pd.read_csv('C:\\Users\\KRIOSOFT\\Documents\\Python Scripts\\DB_METRICS.csv')

In [3]:
data

,HOUR1,FULLDATE,FECHA,TIME,ENDFECHA,ENDTIME,METRIC,COUNT1,VALUE,QUEUEID,WRAPUPCODEID,DNIS,MEDIATYPECODE,DIRECTIONCODE,USERID,PURPOSECODE
0,10:00:00,2022-04-01 10:00:00,2022-04-01,10:00:00,2022-04-01,11:00:00,34,1.0,181.707,DBD8F5BD-EE31-4300-A08F-D747E94C2BC0,00000000-0000-0000-0000-000000000000,19419230506,1,2,3170E7CD-2737-4FD1-A3D0-2D92D4A6F5D4,8
1,13:00:00,2022-04-01 13:00:00,2022-04-01,13:00:00,2022-04-01,14:00:00,22,1.0,0.000,9AB77048-9284-4274-92B2-A6286CE427C9,4130E7FC-1B13-4198-8937-14DEDBB37B3D,17753591730,1,1,F23DC3C7-1722-4837-BCC1-420CF7DAC16F,8
2,17:00:00,2022-04-07 17:00:00,2022-04-07,17:00:00,2022-04-07,18:00:00,22,1.0,0.000,DD931B8B-9114-4F12-BB46-7EAE9DF50438,5A27E52F-CA24-42B7-BDAC-F4BEF6CF2387,15617931441,1,1,84E468D1-78BE-42E7-A007-E3F28371729A,8
3,22:00:00,2022-04-05 22:00:00,2022-04-05,22:00:00,2022-04-05,23:00:00,30,1.0,8.865,A5139396-A66C-4F9E-82E5-6AE767547A58,NaN,19169412999,1,1,NaN,4
4,17:00:00,2022-04-07 17:00:00,2022-04-07,17:00:00,2022-04-07,18:00:00,34,1.0,333.116,7C572784-A99C-46FB-9641-5F112DE54785,00000000-0000-0000-0000-000000000000,12398253408,1,2,B2CF204C-8EFD-4881-97F7-EEDD5BFDEB49,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412937,20:00:00,2022-04-07 20:00:00,2022-04-07,20:00:00,2022-04-07,21:00:00,40,1.0,3.832,A5139396-A66C-4F9E-82E5-6AE767547A58,NaN,19169412999,1,1,NaN,4
412938,12:00:00,2022-04-05 12:00:00,2022-04-05,12:00:00,2022-04-05,13:00:00,17,1.0,0.000,DBD8F5BD-EE31-4300-A08F-D747E94C2BC0,00000000-0000-0000-0000-000000000000,17273188055,1,2,C2B0224B-2B32-44A9-9F93-9206BFCC6DA9,8
412939,13:00:00,2022-04-01 13:00:00,2022-04-01,13:00:00,2022-04-01,14:00:00,27,1.0,0.000,78A41966-3E72-4C26-9CC8-BE493D25CBA0,4130E7FC-1B13-4198-8937-14DEDBB37B3D,13212009371,1,2,6D0E7065-FA51-45EC-8F28-F52A97C6EBB4,8
412940,19:00:00,2022-04-07 19:00:00,2022-04-07,19:00:00,2022-04-07,20:00:00,7,1.0,23.000,8ECF1E78-5D0E-44D6-B5E4-77FA25065E7E,91790D5D-9E1D-462F-8372-A3F96398E491,18184890036,1,2,D3AD655D-7112-46BE-8095-BE86FF72955C,8
412941,15:00:00,2022-04-01 15:00:00,2022-04-01,15:00:00,2022-04-01,16:00:00,23,1.0,30.833,DBD8F5BD-EE31-4300-A08F-D747E94C2BC0,36A09004-C098-4344-98EA-1BF6356BF3AF,19419212852,1,1,53E79D7F-490A-43BD-BC45-0B0E3885217D,8

In [11]:
# Extraccion de los valores de la metrica Talk_TIme ( Metric = 23)
Kpi_Metric = data[data["METRIC"].notna()]
Kpi_Talk_Time = Kpi_Metric[Kpi_Metric["METRIC"] == 23]
Kpi_Talk_TIme = Kpi_Talk_Time["METRIC"].value_counts()

In [13]:
# Extraccion del numero total de registros de la  metrica Talk_TIme ( Metric = 23)
Kpi_Count = Kpi_Talk_TIme

In [14]:
print(Kpi_Count)

23    43910
Name: METRIC, dtype: int64

In [15]:
# Extraccion del valor total de la metrica Talk_TIme ( Metric = 23)
Kpi_Value = Kpi_Talk_Time["VALUE"].sum()

In [16]:
print(Kpi_Value)

7044361.065

In [18]:
# funciÃ³n ara sacar KPI de Talk_TIme
def Kpi_Talk_TIme(Kpi_Value, Kpi_Count):
  return Kpi_Value / Kpi_Count

In [19]:
Kpi_Talk_TIme(Kpi_Value, Kpi_Count)

23    160.427262
Name: METRIC, dtype: float64